# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and Execute Update

on:
  push:
    branches: [ main ]
    paths:
      - data-update.csv
      - .github/workflows/node.js.yml
  pull_request:
    branches: [ main ]
    paths:
      - data-update.csv
      - .github/workflows/node.js.yml

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - run: ./install-fonts.bat
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run update
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: Generated images and data
        path: |
          image-update.csv
          result-update/
        if-no-files-found: error

    - name: Auto commit data-normal.csv
      if: ${{ github.event_name == 'push' }}
      # You may pin to the exact commit or the version.
      # uses: stefanzweifel/git-auto-commit-action@49620cd3ed21ee620a48530e81dba0d139c9cb80
      uses: stefanzweifel/git-auto-commit-action@v4.14.1
      with:
        # Commit message
        commit_message: Auto commit data-normal.csv
        # File pattern used for `git add`. For example `src/*.js`
        file_pattern: data-normal.csv
        
    
